name: DockerHub Login and List Images

on: 
  push:
    branches:
      - main

jobs:
  list-docker-images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERMANU }}" | docker login -u ${{ secrets.DOCK_NAME }} --password-stdin

    - name: git check 
      run: echo "This test is to check the secret in gitlab ${{ secrets.DOCK_NAME }}  "

    - name: List DockerHub Images
      run: docker images

    - name: post run 
      if: always
      run: echo "Running for the victory"
